### PR TITLE
Correct the spelling of Mac OS X / macOS.

### PR DESCRIPTION
**Pull request by shlomif**
See https://en.wikipedia.org/wiki/MacOS .

This is part of the CPAN Pull-Req challenge.

### CODE REVIEW

**Comment by rurban** [comment]
I'm sceptical. See your sw_vers on macOS Sierra and see what it reports. it's Mac OS X. Looks like pure marketing

**Comment by shlomif** [comment]
On Fri, 11 Aug 2017 06:57:10 -0700
Reini Urban <notifications@github.com> wrote:

> I'm sceptical. See your sw_vers on macOS Sierra and see what it reports. it's
> Mac OS X. Looks like pure marketing
> 

well, "OSX" and "MacOSX" were never correct spellings.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Google-Discontinues-Services/

Chuck Norris was able to truly appreciate Hamlet, before he read it in the
original Klingon.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by rurban** [comment]
What about darwin instead?

**Comment by rurban** [comment]
I went with darwin instead. replacing POSIX usage from MacOSX/Unix with Mac OS X/macOS/Unix is just too odd.

**Pull request closed without merging**
