### PR TITLE
Fix failed test with gd-2.3.3

### PR DESCRIPTION
**Pull request by hakonhagland**
Fixes [Bug #139399](https://rt.cpan.org/Public/Bug/Display.html?id=139399).

gd-2.3.3 disabled the old GD and GD2 formats by default, which caused test `t/GD.t` to fail.

Tested this PR on macOS 12.0.1.

### CODE REVIEW

**Comment by eserte** [comment]
@hakonhagland I have a fedora system with gd 2.3.2 and GD.t still fails with GD-2.74:
```
#   Failed test 'unable to generate comparison image for test 1: Can't locate object method "newFromGd2" via package "GD::Image" at (eval 16) line 1.
# '
#   at t/GD.t line 259.
Can't locate object method "newFromGd2" via package "GD::Image" at t/GD.t line 80.
# Looks like your test exited with 255 just after 3.
t/GD.t .................... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 12/14 subtests 
```

**Comment by hakonhagland** [comment]
@eserte Thanks for the report. Does it also fail with GD-2.73 ?

**Comment by eserte** [comment]
2.73 is fine:
```
# Testing gd 2.3.2 using gd2 support.
# gd: 2.3.2, files: ./test_data/images/t7/7-00.gd2 ./test_data/images/t7/7-01.gd2
# ignore corrupt png error messages...
GD Warning: gd-png: fatal libpng error: IHDR: CRC error
GD Warning: gd-png error: setjmp returns error condition 1
t/GD.t .................... ok
```

**Comment by hakonhagland** [comment]
@eserte Thanks for testing, I tried now on Ubuntu 21.10 with GD-2.74 and gd 2.3.0, and I do not get any test failures here. So it is difficult for me to judge what is the problem without being able to reproduce the issue. Would you be able to investigate this in more details? Which version of fedora are you using? Which version of perl?

**Comment by rurban** [comment]
Slaven, file as new bug #74
I've added GD probes, so it should be better not worse. Also on my fedora it works. Interesting

**Pull request merged**
