### PR TITLE
Add the Windows BMP

### LINKED ISSUE #48: please add support for BMP to GD::Image
libgd has included Windows Bitmap [.bmp support](https://libgd.github.io/manuals/2.3.3/files/gd_bmp-c.html) (`gdImageBmp` and `gdImageCreateFromBmp` and associated) since [libgd 2.1.0-alpha1](https://github.com/libgd/libgd/commit/1a022a579bcbb450d8828d9f2e86205ddabfd40e).

This is _different_ from [WBMP support](https://libgd.github.io/manuals/2.3.3/files/gd_wbmp-c.html) ([WBMP](https://en.wikipedia.org/wiki/Wireless_Application_Protocol_Bitmap_Format "Wireless Application Protocol Bitmap Format") is a monochrome format, whereas Windows [BMP](https://en.wikipedia.org/wiki/BMP_file_format) allows anything from monochrom to full-color images; WMBP format uses gdImageWBMP/gdImageCreateFromWBMP/etc, which you have already implemented with `newFromWBMP` and `->wbmp`).

I have confirmed with GD 2.76 libgd 2.2.5 (strawberry perl v5.32.1) that if I output a GD::Image with `$img->wbmp($fg)`, then no default Microsoft tool (mspaint.exe, Photo Viewer, etc) can read it as a Windows Bitmap (.bmp), because it's not a valid Windows bitmap file.  But if I get a tool (like ImageMagick) that understands the monochrome WBMP format, it reads it just fine.  Similarly, `->newFromWBMP` cannot read a standard Windows .bmp file. 

There is no `GD::Image::newFromBmp()` or `->bmp()` pair for input/output of the Windows Bitmap format (`Undefined subroutine &GD::Image::newFromBmp`).

Since `gdImageBmp` and `gdImageCreateFromBmp` already exist in libgd 2.1 and newer (and are thus present in my libgd 2.2.5 or in the libgd 2.3.3 that you've supported since at least v2.74), it would be really nice if support for that feature of libgd could be added to GD::Image.  (If you don't want to try to auto-identify it for `GD::Image::new()`, that's fine with me.)

But whether or not it gets added, the documentation for `GD::Image->newFromWBMP` should be changed for two things: 
1) Since WBMP is not a Windows BMP, and is not compatible with the windows bitmap format, it shouldn't say it is.
2) Since WBMP is a monochrome format, a truecolor option isn't needed.

Thank you.

### PR DESCRIPTION
**Pull request by pryrt**
I added the functions for the Windows BMP

- I tried to follow your coding style, and mostly implemented it by copying the WBMP-equivalent functions and renaming them
- I included the `$options .= "WINDOWS_BMP"` and `#define HAVE_BMP` processing, to make sure it's only there for libgd >= v2.1.0
- it passes your [original test suite](https://github.com/pryrt/Perl-GD/actions/runs/5100084115)
- when I added my new test (to confirm that it can read a windows.bmp file), it passed on my windows machine, but I don't know how to get it to update the MANIFEST.git, so it's failing that test on ubuntu, and thus not moving forward.  I am hoping you know how to fix this one.

Other than that, I hope this is at least a sufficient starting point so that the next release can include the Windows BMP support that's already in libgd since v2.1.0

closes #48

### CODE REVIEW

**Comment by rurban** [comment]
There is also a windows linking error

**Comment by pryrt** [comment]
I don't have any linking errors when I link in my windows setup.  (There are lots of warnings, but there usually are for XS, in my experience)

[my-make-results-were-ok.txt](https://github.com/lstein/Perl-GD/files/11583056/my-make-results-were-ok.txt)

It built then passed the test suite with the normal incantation:
```
perl Makefile.PL
gmake
gmake test
```

Could you be more specific?

**Comment by rurban** [comment]
I squashed and fixed it a bit in the `bmp` branch

**Comment by rurban** [comment]
Thanks, merged

**Pull request closed without merging**
